version: '3.8'

services:
  # 1. GATEWAY (A Portaria Única - Ponto de Entrada)
  gateway:
    build:
      context: ./HelpDesk.Gateway
    container_name: helpdesk-gateway
    ports:
      - "5281:80"  # Porta que você acessa no navegador
    depends_on:
      - api-helpdesk
      - catalogo-api
    networks:
      - helpdesk-internal-net

  # 2. SERVICE A (Sua API Python - Tickets)
  api-helpdesk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helpdesk-api
    # Removi a porta 5000 do host para forçar o uso do Gateway (Segurança)
    environment:
      DATABASE_URL: postgresql://postgres:SenhaForte123@db-helpdesk:5432/postgres
    depends_on:
      - db-helpdesk
    networks:
      - helpdesk-internal-net

  # 3. SERVICE B (Microsserviço de Catálogo do Victor)
  catalogo-api:
    build:
      context: ./GestaoPedidos.Catalogo 
    container_name: catalogo-api
    networks:
      - helpdesk-internal-net

  # 4. BANCO DE DADOS (Persistência)
  db-helpdesk:
    image: postgres:15-alpine
    container_name: helpdesk-db
    environment:
      POSTGRES_PASSWORD: SenhaForte123
    ports:
      - "5432:5432"
    volumes:
      - helpdesk-data:/var/lib/postgresql/data
    networks:
      - helpdesk-internal-net

# REDE INTERNA: Garante que os serviços se comuniquem pelo nome 
networks:
  helpdesk-internal-net:
    driver: bridge

volumes:
  helpdesk-data: