version: '3.8'

services:
  # 1. BROKER DE MENSAGENS
  rabbitmq:
    image: rabbitmq:3-management
    container_name: helpdesk-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - helpdesk-internal-net

  # 2. GATEWAY (.NET)
  gateway:
    build:
      context: .
      dockerfile: HelpDesk.Gateway/Dockerfile
    container_name: helpdesk-gateway
    ports:
      - "5281:8080" # Alterado de 80 para 8080 para alinhar com o .NET 8
    depends_on:
      - rabbitmq
    networks:
      - helpdesk-internal-net

  # 3. API PYTHON 
  api-helpdesk:
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD
    container_name: helpdesk-api
=======
    container_name: helpdesk-api-helpdesk-1
>>>>>>> 1b56b8ca367133de7db8e3388180714aa33b6e6c
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://postgres:SenhaForte123@db-helpdesk:5432/postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - db-helpdesk
      - rabbitmq
    networks:
      - helpdesk-internal-net

  # 4. BANCO DE DADOS (PostgreSQL)
  db-helpdesk:
    image: postgres:15-alpine
<<<<<<< HEAD
    container_name: helpdesk-db
=======
    container_name: helpdesk-db-helpdesk-1
>>>>>>> 1b56b8ca367133de7db8e3388180714aa33b6e6c
    environment:
      POSTGRES_PASSWORD: SenhaForte123
    ports:
      - "5432:5432"
    volumes:
      - helpdesk-data:/var/lib/postgresql/data
    networks:
      - helpdesk-internal-net

  # 5. CACHE DISTRIBUÍDO (Redis)
  helpdesk-cache:
    image: redis:7-alpine
    container_name: helpdesk-cache
    ports:
      - "6379:6379"
    networks:
      - helpdesk-internal-net

networks:
  helpdesk-internal-net:
    driver: bridge

  helpdesk-cache:
    image: redis:7-alpine
    container_name: helpdesk-cache
    ports:
      - "6379:6379"

  helpdesk-rabbitmq:
    image: rabbitmq:3-management
    container_name: helpdesk-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  helpdesk-gateway:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: helpdesk-gateway
    ports:
      - "5281:8080"
    volumes:
      - ./HelpDesk.Gateway:/app
    working_dir: /app
    command: dotnet watch run --urls http://0.0.0.0:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - helpdesk-cache
      - helpdesk-rabbitmq

volumes:
  helpdesk-data: