version: '3.8'

services:
  # 1. BROKER DE MENSAGENS
  rabbitmq:
    image: rabbitmq:3-management
    container_name: helpdesk-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - helpdesk-internal-net

  # 2. GATEWAY (.NET)
  gateway:
    build:
      context: .
      dockerfile: HelpDesk.Gateway/Dockerfile
    container_name: helpdesk-gateway
    ports:
      - "5281:8080" # Alterado de 80 para 8080 para alinhar com o .NET 8
    depends_on:
      - rabbitmq
    networks:
      - helpdesk-internal-net

  # 3. API PYTHON 
  api-helpdesk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helpdesk-api
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://postgres:SenhaForte123@db-helpdesk:5432/postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - db-helpdesk
      - rabbitmq
    networks:
      - helpdesk-internal-net

  # 4. BANCO DE DADOS (PostgreSQL)
  db-helpdesk:
    image: postgres:15-alpine
    container_name: helpdesk-db
    environment:
      POSTGRES_PASSWORD: SenhaForte123
    ports:
      - "5432:5432"
    volumes:
      - helpdesk-data:/var/lib/postgresql/data
    networks:
      - helpdesk-internal-net

  # 5. CACHE DISTRIBUÍDO (Redis)
  helpdesk-cache:
    image: redis:7-alpine
    container_name: helpdesk-cache
    ports:
      - "6379:6379"
    networks:
      - helpdesk-internal-net

networks:
  helpdesk-internal-net:
    driver: bridge

volumes:
  helpdesk-data: