sonar.projectKey=HelpDesk_Projeto
sonar.organization=marcosviniciosmendesdelima
sonar.sources=.
sonar.exclusions=**/*.bin,**/*.obj,**/tests/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.host.url=https://sonarcloud.io