sonar.projectKey=HelpDesk_Projeto
sonar.organization=marcosviniciosmendesdelima
sonar.host.url=https://sonarcloud.io

# Define onde está o código fonte (Python)
sonar.sources=src

# Define onde estão os testes
sonar.tests=tests

# Configuração para relatórios de cobertura do Python (pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml

# Exclui pastas que não fazem parte do código fonte
sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/*.pyc,**/tests/**,**/migrations/**
