name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore helpdesk-tickets.sln
      - name: Build
        run: dotnet build helpdesk-tickets.sln --no-restore

      # Run the test project and generate OpenCover output in the TestResults folder
      - name: Run Tests
        run: dotnet test tests/HelpDesk.Gateway.Tests/HelpDesk.Gateway.Tests.csproj --no-restore --verbosity normal --collect:"XPlat Code Coverage;Format=opencover" --results-directory ./tests/HelpDesk.Gateway.Tests/TestResults

      # Upload the generated coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tests/HelpDesk.Gateway.Tests/TestResults/**/*.opencover.xml

  sonar-analysis:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Baixamos o artefato para a raiz
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ./
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=HelpDesk_Projeto
            -Dsonar.organization=marcosviniciosmendesdelima
            -Dsonar.sources=.
            -Dsonar.cs.opencover.reportsPaths=tests/HelpDesk.Gateway.Tests/TestResults/**/coverage.opencover.xml