name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
      # PASSO NOVO: Salvar o relatório de cobertura para o próximo job
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: /**/coverage.opencover.xml

  sonar-analysis:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # PASSO NOVO: Baixar o relatório salvo pelo job anterior
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=HelpDesk_Projeto
            -Dsonar.organization=marcosviniciosmendesdelima
            -Dsonar.sources=.
            -Dsonar.cs.opencover.reportsPaths=coverage.opencover.xml